Fix for crystal 0.36 compiler error.
A minor change to fix the following error
```
In lib/net_sample/src/net_sample/ping/icmp.cr:130:5

 130 | class EchoRequest < EchoData
       ^
Error: abstract `def NetSample::Ping::ICMP::Data#data(io)` must be implemented by NetSample::Ping::ICMP::EchoRequest
```